command_config:
  command_prefix: "."
  help_command: "<default-help-command>"
  self_bot: False

  
#  template:
#    name:
#    help_long: 
#    help_brief:
#    help_usage:
#    aliases:
#    enabled:
#    

API_config:
  token: "Njc2OTE5NTc0Njc5MjU3MTU4.XkMsew.f6xOinn7UbTf9T610Esh8xyXzgM"
